# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c648f16ffb6f14fdae3f7efa850e028a5ada2cb366d50cbbda185731592c30ef7b42d37142dc6a4b53a31950903c4c5a6b3b9f09b3ecbce46a034aff9e567ca

test:
  secret_key_base: 815f82fdbffdd082be91084a7df2293cb6a07441a3bd0f2d2f064465841e6559889a4c8191cc4859e0cc1ba7bada6e43ec614dafe5ce165f5683ad5f4c7082ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
